language: node_js
node_js:
    - "6"
    - "7"
    - "8"
    - "10"
cache:
    directories:
        - node_modules
install:
    - yarn
script:
    - yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
